### ISSUE TITLE
Dig deeper in sentences we translate badly to try and identify common failure themes

### ISSUE THREAD

**Issue by marco-c** [mozilla/firefox-translations-evaluation#18]

**Comment by evgenyrp** [comment]
Since the code was moved to https://github.com/mozilla/firefox-translations-models/tree/main/evals, we're archiving this repo. Please consider creating an issue in https://github.com/mozilla/firefox-translations-models or https://github.com/mozilla/firefox-translations-training if this one is still relevant.
