### ISSUE TITLE
Train a model to identify "good enough" translations

### ISSUE THREAD

**Issue by marco-c** [mozilla/firefox-translations-evaluation#19]
We could collect labels ala snorkel with a LLM or by translating sentences by other services.

**Comment by evgenyrp** [comment]
Since the code was moved to https://github.com/mozilla/firefox-translations-models/tree/main/evals, we're archiving this repo. Please consider creating an issue in https://github.com/mozilla/firefox-translations-models or https://github.com/mozilla/firefox-translations-training if this one is still relevant.
